# This is a temporary file to allow us to land a new set of linter rules in a
# series of manageable patches instead of one gigantic PR. It disables some of
# the new lints that are already failing on this plugin, for this plugin. It
# should be deleted and the failing lints addressed as soon as possible.

include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    # Increase the severity of the unused_import hint.
    unused_import: warning
    # There are currently 10k violations in test/ and tool/.
    always_declare_return_types: ignore
    # There are currently 5000 violations in lib/. This just does not fit well
    # with the analyzer team's style.
    omit_local_variable_types: ignore
    # There are currently 3360 violations in lib/.
    prefer_single_quotes: ignore
    # Ignoring "style" lint rules from pedantic for now. There are pre-existing
    # violations that need to be cleaned up. Each one can be cleaned up and
    # enabled according to the value provided.
    # TODO(srawlins): At the time of writing, 500 violations in lib/. The fix
    # is mechanical, via `dartfmt --fix-doc-comments`.
    slash_for_doc_comments: ignore
    # There are currently 2000 violations in lib/.
    unnecessary_this: ignore

linter:
  rules:
    - avoid_unused_constructor_parameters
    - empty_statements
    - unnecessary_brace_in_string_interps